"""Core evolutionary loop for the Evolve framework.

This module implements the generation-by-generation evolutionary search that
automatically improves code by iteratively mutating and selecting candidates.
Three modes are supported:

* ``no_evolution``    — baseline; keeps the original code unchanged.
* ``random_mutation`` — random code edits only; no AI involved.
* ``llm_guided``      — random mutations plus periodic LLM improvement calls
                        (45 % of children are generated by the local Ollama model).

Key design choices
------------------
* Parallel evaluation via ``ThreadPoolExecutor`` (4 workers) so all candidates
  in a generation are scored simultaneously — 4× faster than sequential.
* Adaptive mutation rate: decays over generations (exploitation) but spikes
  when the population stagnates (exploration).
* The ``on_generation`` callback lets the Streamlit UI update in real time
  without coupling the evolution logic to the UI layer.
"""
from __future__ import annotations

import random
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from typing import List

from ..cache.cache import FitnessCache
from ..llm.base import LLMClient
from ..llm.ollama_client import OllamaLLM
from .mutations import mutate, mutate_with_meta
from .types import Candidate, GenerationResult


def _sanitize(code: str) -> str:
    """Remove duplicate class definitions from evolved code.

    When the LLM appends a new class definition without removing the old one
    the resulting code has two (or more) ``class MyAgent:`` blocks.  This
    helper keeps only the last (most-evolved) definition so the file stays
    valid and runnable.

    Falls back to returning the original code unchanged if sanitisation fails.

    Parameters
    ----------
    code : str
        Python source code that may contain duplicate class definitions.

    Returns
    -------
    str
        Cleaned Python source code with at most one definition per class.
    """
    try:
        return OllamaLLM._sanitize_code(code)
    except Exception:
        return code


@dataclass
class EvolutionConfig:
    """Immutable configuration bundle passed to the Evolver at creation.

    All values are read from ``config.yaml`` by ``runner.run_experiment()``
    and packed here so the Evolver has a single, explicit dependency rather
    than a loose bag of keyword arguments.

    Attributes
    ----------
    generations : int
        Total number of evolutionary rounds to run.
    population_size : int
        How many code candidates to maintain simultaneously each generation.
    top_k : int
        Number of elite (best-scoring) candidates that survive unchanged into
        the next generation.  Must be < population_size.
    mutation_rate : float
        Starting probability (0–1) that a child will be mutated rather than
        cloned from a parent.  The evolver adjusts this adaptively at runtime.
    """

    generations: int
    population_size: int
    top_k: int
    mutation_rate: float


class Evolver:
    """Runs the evolutionary search for a single problem and mode.

    The Evolver is stateless between ``run()`` calls — it can be called
    multiple times (once per mode) without re-initialisation.

    Parameters
    ----------
    cfg : EvolutionConfig
        Evolution hyper-parameters (generations, population size, etc.).
    llm : LLMClient
        LLM backend used to generate AI-guided children.  The evolver
        calls ``llm.improve(prompt, code)`` for 45 % of children in
        ``llm_guided`` mode.
    cache : FitnessCache
        Fitness cache that avoids re-evaluating identical or near-duplicate
        code strings.
    templates : list of str
        Pre-written algorithm code strings (from ``data/templates/``)
        used by mutation operators as replacement bodies.
    evaluator : MatrixWrapper | PacmanWrapper | PseudocodeWrapper
        Problem-specific scorer.  Must implement ``evaluate(code) -> (float, dict)``.
    prompt : str
        Natural-language description of the optimisation goal sent to the LLM,
        e.g. ``"Reduce matrix operations while staying correct."``
    """

    def __init__(
        self,
        cfg: EvolutionConfig,
        llm: LLMClient,
        cache: FitnessCache,
        templates: List[str],
        evaluator,
        prompt: str,
    ):
        self.cfg = cfg
        self.llm = llm
        self.cache = cache
        self.templates = templates
        self.evaluator = evaluator
        self.prompt = prompt

    def run(
        self,
        base_code: str,
        mode: str,
        on_generation=None,
    ) -> List[GenerationResult]:
        """Execute the full evolutionary loop for one mode and return the history.

        Algorithm overview per generation
        ----------------------------------
        1. Evaluate all candidates in parallel (``ThreadPoolExecutor``, 4 workers).
        2. Sort by fitness descending; save snapshot as ``GenerationResult``.
        3. Print progress to terminal; fire ``on_generation`` callback for live UI.
        4. Track stagnation; adjust ``adaptive_mutation_rate`` accordingly.
        5. Build next generation:
           - Copy elite candidates (``top_k``) unchanged.
           - Fill remaining slots: for ``llm_guided`` mode 45 % of children
             come from ``llm.improve()``; the rest are random mutations or clones.
        6. Repeat until ``generations`` reached (or break immediately for
           ``no_evolution`` mode after the first evaluation).

        Parameters
        ----------
        base_code : str
            The seed Python source code from which the population is seeded.
        mode : str
            One of ``"no_evolution"``, ``"random_mutation"``, ``"llm_guided"``.
        on_generation : callable, optional
            Called after each generation with keyword arguments:
            ``(mode, gen, total_gens, best_fitness, metrics, elapsed)``.
            Used by the Streamlit dashboard for live chart updates.
            Exceptions inside this callback are silently swallowed so they
            can never crash the evolution loop.

        Returns
        -------
        list of GenerationResult
            One entry per generation.  Length == ``cfg.generations`` for
            mutation modes, or 1 for ``no_evolution``.
        """
        population = self._init_population(base_code, mode=mode)
        history: List[GenerationResult] = []

        # Adaptive mutation rate (starts high, decreases over time)
        initial_mutation_rate = self.cfg.mutation_rate
        best_fitness_ever = float('-inf')
        stagnation_count = 0

        print(f"\n{'='*60}")
        print(f"[Evolver] Mode: {mode.upper()} | Generations: {self.cfg.generations} | Population: {self.cfg.population_size}")
        print(f"{'='*60}")
        run_start = time.time()

        for gen in range(self.cfg.generations):
            gen_start = time.time()
            # Evaluate all candidates in parallel (matrix/simulation evals are CPU-bound
            # and independent; LLM evals share the GPU but Ollama queues them safely)
            with ThreadPoolExecutor(max_workers=4) as pool:
                futures = {pool.submit(self._evaluate, cand): cand for cand in population}
                for future in as_completed(futures):
                    future.result()  # propagate any exception

            population.sort(key=lambda c: c.fitness or 0.0, reverse=True)
            best = population[0]
            history.append(GenerationResult(gen, population[:], best))

            gen_elapsed = time.time() - gen_start
            best_fitness = best.fitness or 0.0
            metrics_str = " | ".join(
                f"{k}: {v:.2f}" for k, v in (best.metrics or {}).items()
            )
            print(
                f"  Gen {gen+1:>3}/{self.cfg.generations}"
                f" | Best Fitness: {best_fitness:>8.4f}"
                f" | {metrics_str}"
                f" | Time: {gen_elapsed:.2f}s"
            )

            # Fire UI callback for live streaming
            if on_generation is not None:
                try:
                    on_generation(
                        mode=mode,
                        gen=gen + 1,
                        total_gens=self.cfg.generations,
                        best_fitness=best_fitness,
                        metrics=best.metrics or {},
                        elapsed=gen_elapsed,
                    )
                except Exception:
                    pass  # never let a UI callback crash the evolution loop
            
            # Track improvement for adaptive behavior
            if best.fitness and best.fitness > best_fitness_ever:
                best_fitness_ever = best.fitness
                stagnation_count = 0
            else:
                stagnation_count += 1

            if mode == "no_evolution":
                break
            
            # Adaptive mutation rate: increase if stagnating
            if stagnation_count > 2:
                adaptive_mutation_rate = min(1.0, initial_mutation_rate * 1.5)
            else:
                # Decay mutation rate over generations for exploitation
                adaptive_mutation_rate = initial_mutation_rate * (1.0 - 0.3 * gen / self.cfg.generations)

            elites = population[: self.cfg.top_k]
            next_pop = elites[:]

            while len(next_pop) < self.cfg.population_size:
                parent = random.choice(elites)
                if mode == "llm_guided" and random.random() < 0.45:
                    new_code = self.llm.improve(self.prompt, parent.code)
                    meta = {
                        "op": "llm_improve",
                        "op_description": f"LLM (Ollama/local) refined parent code; parent fitness={parent.fitness:.4f}" if parent.fitness else "LLM refinement",
                        "parent_fitness": str(parent.fitness),
                    }
                else:
                    if random.random() < adaptive_mutation_rate:
                        new_code, mut_meta = mutate_with_meta(parent.code, self.templates)
                        new_code = _sanitize(new_code)
                        meta = {**mut_meta, "parent_fitness": str(parent.fitness)}
                    else:
                        new_code = parent.code
                        meta = {
                            "op": "clone",
                            "op_description": f"Exact clone of elite parent; parent fitness={parent.fitness:.4f}" if parent.fitness else "Clone of parent",
                            "parent_fitness": str(parent.fitness),
                        }
                next_pop.append(Candidate(code=new_code, meta=meta))

            population = next_pop

        total_elapsed = time.time() - run_start
        final_best = history[-1].best
        print(f"\n[Evolver] Mode '{mode}' complete | Total Time: {total_elapsed:.2f}s | Best Fitness: {final_best.fitness or 0.0:.4f}")
        print(f"{'='*60}\n")
        return history

    def _init_population(self, base_code: str, mode: str = "") -> List[Candidate]:
        """Create the starting population before generation 0.

        For ``no_evolution`` mode returns a list of exactly one candidate
        (the unmodified base code).

        For other modes the population is seeded with the base code and then
        filled to ``population_size`` by applying ``mutate_with_meta()``
        repeatedly.  Any mutation that produces a syntax error is discarded
        and retried.  After 50 failed attempts, a clone of the base is
        accepted as a safety valve so the loop never stalls indefinitely.

        Parameters
        ----------
        base_code : str
            The seed Python source code.
        mode : str
            Evolution mode string (controls whether mutations are applied).

        Returns
        -------
        list of Candidate
            Initial population of length ``population_size`` (or 1 for
            ``no_evolution``).
        """
        base = Candidate(code=base_code, meta={"op": "base", "op_description": "Original base code (seed)"})
        # no_evolution: baseline uses ONLY the original code — no mutations in initial pop
        if mode == "no_evolution":
            return [base]
        population = [base]
        import ast as _ast
        attempts = 0
        while len(population) < self.cfg.population_size:
            new_code, meta = mutate_with_meta(base_code, self.templates)
            new_code = _sanitize(new_code)
            # Reject syntactically invalid mutations (keep trying, but cap attempts)
            try:
                _ast.parse(new_code)
                population.append(Candidate(code=new_code, meta=meta))
            except SyntaxError:
                attempts += 1
                if attempts > 50:  # safety valve: accept even invalid after 50 fails
                    population.append(Candidate(code=base_code, meta={"op": "clone", "op_description": "Clone (mutation rejected)"}))
        return population

    def _evaluate(self, cand: Candidate) -> None:
        """Score a single candidate and store the result on the object in place.

        First checks the ``VectorCache`` for an exact or near-duplicate match
        to avoid redundant evaluation.  On a cache miss, delegates to
        ``self.evaluator.evaluate(cand.code)`` and writes the result back to
        the cache for future reuse.

        This method is called concurrently via ``ThreadPoolExecutor`` so it
        must be thread-safe.  The evaluators and cache are all thread-safe
        for this use-case (no shared mutable state beyond the JSONL append,
        which is atomic on all supported OS).

        Parameters
        ----------
        cand : Candidate
            The candidate whose ``fitness`` and ``metrics`` fields will be
            populated.  Modified in place.
        """
        cached = self.cache.get(cand.code)
        if cached is not None:
            cand.fitness = cached["fitness"]
            cand.metrics = {k: float(v) for k, v in cached["metrics"].items()}
            return
        fitness, metrics = self.evaluator.evaluate(cand.code)
        cand.fitness = fitness
        cand.metrics = metrics
        self.cache.set(cand.code, fitness, metrics)
